name: 'JIRA Link Action'
description: 'Automatically adds, updates, or removes a JIRA ticket link in a PR based on the PR title.'
author:
  name: 'CodeNameGrant'
branding:
  icon: 'link'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token (usually secrets.GITHUB_TOKEN)'
    required: true

  jira-base-url:
    description: 'Base URL for your JIRA instance (eg: https://yourcompany.atlassian.net)'
    required: true

  jira-link-mode:
    description: 'Where to add the JIRA link: body-start, body-end'
    required: false
    default: 'body-start'
    options:
      - body-start
      - body-end

  issue-pattern:
    description: 'Custom regex to match JIRA issues (default: "[A-Z]+-\\d+")'
    required: false

runs:
  using: 'node20'
  # dist/index.js is compiled from src/index.ts; do NOT commit dist/ to main
  main: 'dist/index.js'
