name: Add JIRA Links
on:
  pull_request:
    branches:
      - master
    types: [opened, edited, reopened, synchronize]

permissions:
  pull-requests: write

jobs:
  add-jira-links:
    runs-on: ubuntu-latest
    steps:
      - uses: codenamegrant/jira-pr-link-action@v0.0.10
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-base-url: 'https://test-company.atlassian.net'
          jira-link-mode: 'body-start'
          # issue-pattern: '(MyProject-\d+)'
